[extend]
useDefault = true

[allowlist]
description = "Global allowlist"

# Ignore placeholder/example values
regexTarget = "match"
regexes = [
  '''envVars.S3_ENCRYPTION_KEY''', # Don't know why this is returned by gitleaks
  '''b1f742f0-6687-4d84-8f65-d92872d769e9''', # Has been revocked
  '''YOUR_TOKEN''',
  '''REDACTED''',
  '''a1b2c3d4e5f6a7b8c9d0e1f2a3b4c5d6e7f8a9b0c1d2e3f4a5b6c7d8e9f0a1b2''', # It's a random key not used anywhere
  '''REDIS_HOST''', # Used to mimick managed Redis behaviour, it's not a real secret
]
